name: Treo Tool JS

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 */6 * * *' 

jobs:
  build-and-run:
    runs-on: ubuntu-latest 

    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v4

      # Gọi Node.js phiên bản mới nhất hiện tại
      - name: Cài đặt Node.js mới nhất
        uses: actions/setup-node@v4
        with:
          node-version: 'current' 

      # Chỉ cần cài đặt thư viện 'colors', các thư viện khác đã có sẵn
      - name: Cài đặt thư viện bên ngoài
        run: npm install colors
      - name:
        run: npm install gradient-string
      - name:
        run: npm install uuid
      - name:
        run: npm install user-agents

      # Chạy file với hệ số
      - name: Chạy Tool
        run: node cf-pro.js bypass 600 100 proxy-list.txt 220 https://rate-limit-1.dstatbot.win/fgluh4cS
